"""add_ephemeral_signature

Revision ID: a94a1cecfdaa
Revises: afe555914412
Create Date: 2025-12-28 15:51:35.782793

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a94a1cecfdaa'
down_revision = 'afe555914412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ephemeral_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'ephemeral_signature')
    # ### end Alembic commands ###
