"""Initial migration

Revision ID: afe555914412
Revises: 
Create Date: 2025-12-24 12:40:38.400190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe555914412'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ecdsa_public_key', sa.Text(), nullable=True),
    sa.Column('ecdh_public_key', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_request', 'contact_requests', ['sender_id', 'receiver_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('ephemeral_public_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_is_delivered', 'messages', ['is_delivered'], unique=False)
    op.create_index('ix_messages_recipient_delivered', 'messages', ['recipient_id', 'is_delivered'], unique=False)
    op.create_index('ix_messages_recipient_timestamp', 'messages', ['recipient_id', 'timestamp'], unique=False)
    op.create_index('ix_messages_sender_timestamp', 'messages', ['sender_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index('ix_messages_sender_timestamp', table_name='messages')
    op.drop_index('ix_messages_recipient_timestamp', table_name='messages')
    op.drop_index('ix_messages_recipient_delivered', table_name='messages')
    op.drop_index('ix_messages_is_delivered', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_unique_request', table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
