"""add_ecdh_signature

Revision ID: cda8e6e74099
Revises: a94a1cecfdaa
Create Date: 2025-12-29 11:53:35.892130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda8e6e74099'
down_revision = 'a94a1cecfdaa'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ecdh_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ecdh_signature')
    # ### end Alembic commands ###